# Generated by Django 4.2.13 on 2026-04-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supabase_uid", models.UUIDField(db_index=True, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("xp_points", models.IntegerField(default=0)),
                ("streak_count", models.IntegerField(default=0)),
                ("last_active_date", models.DateField(blank=True, null=True)),
                ("badges", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_profiles",
            },
        ),
    ]
