# Generated by Django 4.2.13 on 2026-04-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "track_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("practitioner", "Practitioner"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="book", max_length=50)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("estimated_minutes", models.IntegerField(default=15)),
                ("xp_reward", models.IntegerField(default=50)),
                (
                    "skill_category",
                    models.CharField(
                        choices=[
                            ("nlp", "NLP"),
                            ("computer_vision", "Computer Vision"),
                            ("tabular", "Tabular Data"),
                            ("reinforcement_learning", "Reinforcement Learning"),
                            ("model_evaluation", "Model Evaluation"),
                            ("data_preprocessing", "Data Preprocessing"),
                            ("fundamentals", "Fundamentals"),
                        ],
                        default="fundamentals",
                        max_length=30,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="curriculum.learningtrack",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content_markdown", models.TextField()),
                ("has_code_challenge", models.BooleanField(default=False)),
                ("starter_code", models.TextField(blank=True)),
                ("solution_code", models.TextField(blank=True)),
                ("test_cases", models.JSONField(default=list)),
                ("order", models.IntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="curriculum.module",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField(default=0)),
                ("lessons_completed", models.JSONField(default=list)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curriculum.module",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("user_profile", "module")},
            },
        ),
    ]
