# Generated by Django 4.2.13 on 2026-04-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(default=0)),
                ("xp_points", models.IntegerField(default=0)),
                ("modules_completed", models.IntegerField(default=0)),
                ("quizzes_passed", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entry",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-xp_points"],
            },
        ),
    ]
